trigger:
- master

pr: none


variables:
  logicAppCIArtifactName: 'logicapp_publish_artifact'

stages:
- stage: Build
  displayName: Build Logic App

  jobs:
  - job: logic_app_build
    displayName: 'Build and publish logic app'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: CopyFiles@2
      displayName: 'Create project folder'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        TargetFolder: 'project_output'

    - task: ArchiveFiles@2
      displayName: 'Create project zip'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/project_output'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true

    - task: PublishPipelineArtifact@1
      displayName: 'Publish project zip artifact'
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        artifact: '$(logicAppCIArtifactName)'
        publishLocation: 'pipeline'

- stage: DeployDEV
  displayName: 'DEV Deployment'
  jobs:
  - deployment: deploy_logicapp_resources
    displayName: Deploy Logic App
    pool:
      vmImage: ubuntu-latest
    environment: DEV
    variables:
      deploymentMode: 'Incremental'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                # Write your commands here
                
                cd "$(System.DefaultWorkingDirectory)"
                ls -l
                
          - task: AzureFunctionApp@1
            displayName: 'Deploy logic app workflows'
            inputs:
              azureSubscription: 'RnD (71e137e0-0593-45df-adbf-4530fff5092b)'
              appType: 'functionapp,workflowapp'
              appName: 'blueprintlogic'
              package: '$(logicAppCIArtifactName)/$(Build.BuildId).zip'
              appSettings: '-SERVICE_BUS_CONN_STRING Endpoint=sb://bpevents.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=3sAm+HXNB2g9C6t4xYOi5YJVhaHHH6f7nnr6UnA1l0Q='
              configurationStrings: '-TOPIC_NAME notification-receive-topic -SUBSCRIPTION_NAME logicapp'
              deploymentMethod: 'zipDeploy'