trigger:
- master

pr: none


variables:
  logicAppCIArtifactName: 'logicapp_publish_artifact'

stages:
- stage: Build
  displayName: Build Logic App

  jobs:
  - job: logic_app_build
    displayName: 'Build and publish logic app'
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: CopyFiles@2
      displayName: 'Create project folder'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        TargetFolder: 'project_output'

    - task: ArchiveFiles@2
      displayName: 'Create project zip'
      inputs:
        rootFolderOrFile: '$(System.DefaultWorkingDirectory)/project_output'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true

    - task: PublishPipelineArtifact@1
      displayName: 'Publish project zip artifact'
      inputs:
        targetPath: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        artifact: '$(logicAppCIArtifactName)'
        publishLocation: 'pipeline'

- stage: DeployDEV
  displayName: 'DEV Deployment'
  jobs:
  - deployment: deploy_logicapp_resources
    displayName: Deploy Logic App
    pool:
      vmImage: ubuntu-latest
    environment: DEV
    variables:
      deploymentMode: 'Incremental'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: Bash@3
            inputs:
              targetType: 'inline'
              script: |
                echo $(Pipeline.Workspace)
                cd "$(Pipeline.Workspace)/$(logicAppCIArtifactName)"
                ls -l
          
          # - task: AzureKeyVault@2
          #   inputs:
          #     azureSubscription: 'RnD (71e137e0-0593-45df-adbf-4530fff5092b)'
          #     KeyVaultName: 'blueprint-vault'
          #     SecretsFilter: 'sbconn'
          #     RunAsPreJob: true
          
          - task: AzureAppServiceSettings@1
            inputs:
              azureSubscription: 'RnD (71e137e0-0593-45df-adbf-4530fff5092b)'
              appName: 'blueprintlogic'
              resourceGroupName: 'blueprint'
              appSettings: |
                [
                  {
                    "name": "SERVICE_BUS_CONN_STRING",
                    "value": "@Microsoft.KeyVault(VaultName=blueprint-vault;SecretName=sbconn)",
                    "slotSettings": false
                  },
                  {
                    "name": "OKTA-CLIENT-ID",
                    "value": "@Microsoft.KeyVault(VaultName=blueprint-vault;SecretName=okta-client-id)",
                    "slotSettings": false
                  },
                  {
                    "name": "OKTA-CLIENT-SECRET",
                    "value": "@Microsoft.KeyVault(VaultName=blueprint-vault;SecretName=okta-client-secret)",
                    "slotSettings": false
                  },
                  {
                    "name": "OKTA-URL",
                    "value": "https://dev-98237100.okta.com/",
                    "slotSettings": false
                  },
                  {
                    "name": "NOTIFICATION_CREATE_API_ENDPOINT",
                    "value": "https://blueprintapi.azure-api.net/sp/create",
                    "slotSettings": false
                  }
                ]

          - task: AzureFunctionApp@1
            displayName: 'Deploy logic app workflows'
            inputs:
              azureSubscription: 'RnD (71e137e0-0593-45df-adbf-4530fff5092b)'
              appType: 'functionapp,workflowapp'
              appName: 'blueprintlogic'
              package: '$(Pipeline.Workspace)/$(logicAppCIArtifactName)/$(Build.BuildId).zip'
              configurationStrings: '-TOPIC_NAME notification-receive-topic -SUBSCRIPTION_NAME logicapp'
              deploymentMethod: 'zipDeploy'